### ISSUE TITLE
 What are your short-term goals?

### ISSUE THREAD

**Issue by szalapski** [joynoele/StocksAndBonds#1]
I see your long term goals.  What are your short-term goals? What do you most want help with? What would you like to end up with in a month?

**Comment by joynoele** [comment]
Things to work on in order of importance:

1. Complete simulation components - this will be my primary focus atm
2. Modularize to allow contributors to play the game with their own constructed AI's. This mean architecting the classes to be call-able (web service? library?) somehow. REST endpoint for each of the functions (setup next year, buy, sell, calculate yield, etc) is a good place to start.
3. Basic AI setup - template out how contributors can plug & play their own AI.
4. Front end design - would be cool to play this as a web app, and/or as an executable with some sort of GUI instead of a console.

Later:
- Setup game play via configuration (# of years, securities beyond the basics, ) instead of hardcoded
- Add test/regression cases where appropriate. I'd like to use this as an experimental area for using something other than MSTest, such as BDD.
- Build AI's using ML.NET technology if possible
- Harness for running simulations and provide in-application AI stats collection and analysis
- Add application logging (serilog!)

For you @szalapski, would recommend either (1) pulling together some ideas for a front end (Vue, or otherwise) or (2) Refactoring solution to use DI and extract classes into new projects if needed. What are you most interested in learning?
